FROM python:3.12-slim

WORKDIR /api

COPY api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY api/ .

EXPOSE 5001

CMD ["gunicorn", "--workers", "2", "--bind", "0.0.0.0:5001", "api:app"]
