apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: notes-app
data:
  default.conf: |
    upstream flask_web {
        server flask-web-service:5000;
    }

    upstream flask_api {
        server flask-api-service:5001;
    }

    server {
        listen 80;
        server_name _;

        location /api/ {
            proxy_pass http://flask_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://flask_web;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
